name: "Silentium"
version: "${version}"
main: "me.mcyeet.silentium.Silentium"
api-version: "1.16"
softdepend: [Vault, PacketEvents]
authors: [MrMcyeet]
libraries:
  - com.github.ben-manes.caffeine:caffeine:3.1.8
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.0
  - dev.jorel:commandapi-bukkit-shade:9.3.0
